# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3c9180c07b4ae10900365c150df4f3d7e2dfd79673df0d8ec8ff7fa91abc1807fd98ee0f94da3357a39a0e809310c80bfcfe16cfd4f401aa2d66b389ca2e47d

test:
  secret_key_base: 702a85ed42af73dc7a15da341bcc11b4f7d07eefcaea2a365083e42db9bba723448e083210ad6221eff15d87ef7c1f1bd66beb0cad5bec164500f247b4c8e9ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
